# Header
menu:
  主页: / 
  归档: /archives/
  说说: /talks/
  友链: /link/ 
  留言: /comments/
  模板: /wheels/
rss: /atom.xml

home:
  style: default           # default, detail

favicon:                   # Path to the custom favicon (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: true            # Display banner
  url: /img/banner.png
  position: center         # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true         # Display banner on all pages

# Appearence
hue: 270                   # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
      - archive
      - recent_posts

# Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5

# Personal info
avatar: /img/myavatar.jpg
author: EveSunMaple
subtitle: 一名喜欢折腾的OIer
links:
  - name: email
    icon: fa-solid fa-envelope
    url: mailto:evesunmaple@outlook.com
  - name: Discord
    icon: fa-brands fa-discord      # Find icon codes at https://fontawesome.com/search
    url: https://discord.gg/JhXbkHw4XK
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/EveSunMaple
  - name: BiliBili
    icon: fa-brands fa-bilibili
    url: https://space.bilibili.com/438392347?spm_id_from=333.1007.0.0
  - name: music
    icon: fa-solid fa-music
    url: https://music.saroprock.com

comment:
  valine:
    enable: true # if you want use valine,please set this value is true
    appId: CqO3N7bXHAFURAcDVE1BGQWy-MdYXbMMI # leancloud application app id
    appKey: xxFIHrKeJzP35Sm7jmHCgdhV # leancloud application app key
    pageSize: 10 # comment list page size
    avatar: wavatar # gravatar style https://valine.js.org/#/avatar
    lang: zh-CN # i18n: zh-cn/en
    placeholder: 花径不曾缘客扫，蓬门今始为君开 # valine comment input placeholder(like: Please leave your footprints )
    guest_info: 昵称,邮箱,链接 #valine comment header info
    enableQQ: true
    serverURLs: "https://api.saroprock.com"
    
  # Footer
#copyright: |-
#  <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#  All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>